# Generated by Django 5.2.12 on 2026-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='submission',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
